# Generated by Django 4.1 on 2022-11-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_vehiculo_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cilindrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cilindrada", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="Cantidad",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="Descripcion",
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="imagen",
            field=models.ImageField(default=1, upload_to="files/imagenes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="cilindrada",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.cilindrada",
            ),
            preserve_default=False,
        ),
    ]
