# Generated by Django 4.1 on 2022-11-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_cilindrada_remove_vehiculo_cantidad_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehiculo",
            old_name="imagen",
            new_name="url",
        ),
    ]
