# Generated by Django 4.1 on 2022-11-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_url_vehiculo_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="precio",
            field=models.IntegerField(),
        ),
    ]
