# Generated by Django 4.1 on 2022-11-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_vehiculo_ficha_vehiculo_rendimiento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="ficha",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
