# Generated by Django 4.1 on 2022-11-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_vehiculo_ficha"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="imagen2",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="imagen3",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="imagen4",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
