# Generated by Django 4.1 on 2022-11-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_vehiculo_imagen2_vehiculo_imagen3_vehiculo_imagen4"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="desc",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="desc1",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="desc2",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="desctitulo",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="desctitulo1",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="desctitulo2",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
