# Generated by Django 4.1 on 2022-11-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_vehiculo_desc_alter_vehiculo_desc1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="desctitulo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="desctitulo1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="desctitulo2",
            field=models.CharField(max_length=100),
        ),
    ]
