# Generated by Django 4.1 on 2022-11-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_vehiculo_cantidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateTimeField()),
                ("precio_total", models.IntegerField()),
            ],
        ),
    ]
