# Generated by Django 4.1 on 2022-11-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_vehiculo_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="precio",
            field=models.IntegerField(),
        ),
    ]
