# Generated by Django 4.1 on 2022-11-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_vehiculo_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="desc",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="desc1",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="desc2",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="desctitulo",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="desctitulo1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="desctitulo2",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
