# Generated by Django 4.1 on 2022-11-30 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_vehiculo_desc_alter_vehiculo_desc1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.CharField(default='', max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=10)),
                ('terminos', models.BooleanField(default=True)),
                ('estado', models.BooleanField()),
                ('tipoUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipousuario')),
            ],
        ),
    ]
