# Generated by Django 4.1 on 2022-11-30 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_transmision_alter_vehiculo_transmision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transmision",
            old_name="transmision",
            new_name="nombre",
        ),
    ]
