# Generated by Django 4.1 on 2022-11-30 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_rename_transmision_transmision_nombre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transmision",
            old_name="nombre",
            new_name="transmision",
        ),
    ]
