# Generated by Django 4.1 on 2022-11-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_rename_nombre_transmision_transmision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehiculo",
            old_name="transmision",
            new_name="transmisson",
        ),
    ]
