# Generated by Django 4.1 on 2022-11-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_rename_transmision_vehiculo_transmisson"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehiculo",
            old_name="transmisson",
            new_name="transmision",
        ),
    ]
