# Generated by Django 4.1 on 2022-11-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_rename_transmisson_vehiculo_transmision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="transmision",
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name="Transmision",
        ),
    ]
