# Generated by Django 4.1 on 2022-11-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_alter_vehiculo_transmision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiculo",
            name="transmision",
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="trans",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
