# Generated by Django 4.1 on 2022-11-30 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_remove_vehiculo_transmision_vehiculo_trans"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehiculo",
            old_name="trans",
            new_name="transmision",
        ),
    ]
