# Generated by Django 4.1 on 2022-11-30 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_rename_trans_vehiculo_transmision"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transmision", models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="transmision",
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="transmion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.transmision",
            ),
            preserve_default=False,
        ),
    ]
