# Generated by Django 4.1 on 2022-11-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_transmision_remove_vehiculo_transmision_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehiculo",
            old_name="transmion",
            new_name="transmision",
        ),
    ]
