# Generated by Django 4.1 on 2022-11-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_rename_transmion_vehiculo_transmision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transmision",
            name="transmision",
            field=models.CharField(max_length=40),
        ),
    ]
