# Generated by Django 4.1 on 2022-11-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_alter_transmision_transmision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transmision",
            name="transmision",
        ),
        migrations.AddField(
            model_name="transmision",
            name="tipoVehiculo",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
